# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Try a latest kernel, to hopefully resolve video card issues.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/37bec5a5-226f-41a0-8acf-ebe36fbf4365";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/3D13-2457";
    fsType = "vfat";
  };

  fileSystems."/mnt/alexandria" = {
    device = "alexandria:/mnt/storage";
    fsType = "nfs";
    options = [ "x-systemd.automount" "noauto" "noatime" "soft" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3d13883e-2ccf-46dc-b361-76a0e18ef9a3"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

  hardware.opengl = {
    extraPackages = with pkgs; [
      amdvlk
      rocm-opencl-icd
      rocm-opencl-runtime
    ];
  };

  environment.variables = {
    AMD_VULKAN_ICD = lib.mkDefault "RADV";
  };

  # USB autosuspend behaves poorly for at least mouse, keyboard, and bluetooth dongle.
  services.udev.extraRules = ''
    SUBSYSTEM=="usb", ATTR{product}=="CST Laser Trackball", ATTR{power/control}="on"
    SUBSYSTEM=="usb", ATTR{product}=="USB Keyboard", ATTR{power/control}="on"
    SUBSYSTEM=="usb", ATTR{product}=="CSR8510 A10", ATTR{power/control}="on"
    ACTION=="add", SUBSYSTEM=="video4linux", DRIVERS=="uvcvideo", RUN+="${pkgs.v4l-utils}/bin/v4l2-ctl -d $devnode --set-fmt-video=width=4096,height=2160,pixelformat=MJPG"
  '';

  home-manager.users.jneeman.wayland.windowManager.sway = {
    config.input."1386:183:Wacom_Intuos3_4x6_Pen".map_to_output = "DP-1";
  };
}
