# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Try a latest kernel, to hopefully resolve video card issues.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/37bec5a5-226f-41a0-8acf-ebe36fbf4365";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/3D13-2457";
    fsType = "vfat";
  };

  fileSystems."/mnt/alexandria" = {
    device = "alexandria:/mnt/storage";
    fsType = "nfs";
    options = [ "x-systemd.automount" "noauto" "noatime" "soft" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3d13883e-2ccf-46dc-b361-76a0e18ef9a3"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.opengl = {
    extraPackages = with pkgs; [
      amdvlk
      rocm-opencl-icd
      rocm-opencl-runtime
    ];
  };

  environment.variables = {
    AMD_VULKAN_ICD = lib.mkDefault "RADV";
  };

  # USB autosuspend behaves poorly for at least mouse, keyboard, and bluetooth dongle.
  services.udev.extraRules = ''
    SUBSYSTEM=="usb", ATTR{product}=="CST Laser Trackball", ATTR{power/control}="on"
    SUBSYSTEM=="usb", ATTR{product}=="USB Keyboard", ATTR{power/control}="on"
    SUBSYSTEM=="usb", ATTR{product}=="CSR8510 A10", ATTR{power/control}="on"
    ACTION=="add", SUBSYSTEM=="video4linux", DRIVERS=="uvcvideo", RUN+="${pkgs.v4l-utils}/bin/v4l2-ctl -d $devnode --set-fmt-video=width=4096,height=2160,pixelformat=MJPG"
  '';

  #home-manager.users.jneeman.wayland.windowManager.sway = {
  #  config.input."1386:183:Wacom_Intuos3_4x6_Pen".map_to_output = "DP-3";
  #};
  home-manager.users.jneeman.wayland.windowManager.hyprland = {
    extraConfig = ''
      monitor=DP-3, 3840x2160, 1440x0, 1
      monitor=HDMI-A-1, 2560x1440, 0x0, 1, transform, 3

      workspace=1, monitor:HDMI-A-1
      workspace=2, monitor:HDMI-A-1
      workspace=3, monitor:HDMI-A-1
      workspace=4, monitor:HDMI-A-1
      workspace=5, monitor:HDMI-A-1
      workspace=6, monitor:DP-3
      workspace=7, monitor:DP-3
      workspace=8, monitor:DP-3
      workspace=9, monitor:DP-3
      workspace=0, monitor:DP-3

      windowrule=workspace 1,title:^(.*)(Slack)$

      device {
        wacom-intuos3-4x6-pen {
          output=DP-3
        }
      }
    '';
  };

  home-manager.users.jneeman.programs.waybar.settings.mainBar.cpu = {
    format = pkgs.lib.mkForce "{icon0}{icon1}{icon2}{icon3}{icon4}{icon5}{icon6}{icon7}{icon8}{icon9}{icon10}{icon11}{icon12}{icon13}{icon14}{icon15}{icon16}{icon17}{icon18}{icon19}{icon20}{icon21}{icon22}{icon23}{icon24}{icon25}{icon26}{icon27}{icon28}{icon29}{icon30}{icon31}";
  };
}
